# JWT configuration
jwt:
  secret: "${JWT_SECRET:Q2F0QW5kRG9nU2VjcmV0S2V5MTIzIT8=}"
  expiration: 21600000
spring:
    application:
        name: agendix
    datasource:
        url: jdbc:postgresql://localhost:5432/mydatabase
        username: myuser
        password: secret
        driver-class-name: org.postgresql.Driver

    jpa:
        database: postgresql
        hibernate:
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                hbm2ddl:
                    auto: validate

    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        default-schema: public

    sql:
       init:
           schema-locations: public
           mode: never